Add (unresponsive and unauth) login page and include Semantic UI
Albert-Hadacek/wind-turbines pull request #2
Opened 2022-03-14 13:37 UTC by slurmsmackenzie99

Add icon in the static files directory

2022-03-14 17:53 UTC, Albert-Hadacek commented on pages/account/loginLayout.js
> +      <Message>
This section can be removed as we are not gonna use it :)

2022-03-14 17:56 UTC, Albert-Hadacek commented on pages/index.js
> +        <LoginForm></LoginForm>
Just use <LoginForm/>

2022-03-14 17:59 UTC, Albert-Hadacek requested changes

2022-03-14 17:59 UTC, Albert-Hadacek commented on pages/account/loginLayout.js
> +import React from 'react'
Move this file into a folder outside of pages, lets call it components

2022-03-15 19:00 UTC, slurmsmackenzie99 commented
Can't see why deployment failed
https://vercel.com/deployments/wind-turbines-dvvtb2zz2-albert-hadacek.vercel.app?redirect=1 throws 404

2022-04-15 19:17 UTC, merged